version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/skelebot
    steps:
      - checkout
      - run:
          name: upgrade pip
          command: pip install -U pip
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python setup.py test
