version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/skelebot
    steps:
      - checkout
      - run:
          name: pip env
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: install dependencies
          command: pipenv run pip install -r requirements.txt
      - run:
          name: run tests
          command: pipenv run coverage run --source=skelebot setup.py test && pipenv run coverage report
      - codecov/upload:
          file: {{ coverage_report_filepath }}
          toekn: cb75132d9ffe340a42dd5deea2f0fff43eb61042
